/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "blocks to text",
  "description": "Translate script to text",
  "tags": [],
  "credits": [
    {
      "name": "ScratchBit"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js",
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "id": "target",
      "name": "Only editing target",
      "default": true,
      "type": "boolean"
    },
    {
      "id": "translate",
      "name": "Enable tranlating eg.:motion_movesteps > move steps",
      "default": true,
      "type": "boolean"
    },
    {
      "id": "highlight",
      "name": "Enable highlightJS. (Very buggy)",
      "default": false,
      "type": "boolean"
    }
  ],
  "dynamicDisable": true,
  "tags": [],
  "enabledByDefault": false
};
export default manifest;
